version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm -version
      - npm cache clean --force
      - npm install
    #  - npm -ci
    #  - find . -name "node_modules" -type d -prune -exec rm -rf '{}' +
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls